# Generated by Django 5.2.11 on 2026-02-12 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_applicationsubmission_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When proof of submission was uploaded', null=True),
        ),
        migrations.AlterField(
            model_name='applicationsubmission',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Upload screenshot, image, or PDF confirmation', null=True, upload_to='submission_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='applicationsubmission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Received'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=20),
        ),
    ]
