# Generated by Django 5.2.11 on 2026-02-12 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_applicationsubmission_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Call'), ('PORTAL', 'Portal'), ('OTHER', 'Other')], default='EMAIL', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('FOLLOW_UP', 'Follow Up'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_responses', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='submissions.applicationsubmission')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
    ]
