# Generated by Django 5.2.13 on 2026-04-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_workflow_consultant_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='referral_name',
            field=models.CharField(blank=True, help_text='Name of person who referred (if source=REFERRAL)', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationsubmission',
            name='source',
            field=models.CharField(choices=[('AGENCY', 'Agency Submitted'), ('SELF_APPLIED', 'Self Applied'), ('REFERRAL', 'Referral'), ('EXTERNAL', 'External Portal')], default='AGENCY', help_text='How this application was submitted', max_length=20),
        ),
    ]
