# Generated by Django 5.2.11 on 2026-02-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promptversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promptversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='promptversion',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='prompttestrun',
            name='prompt_version',
        ),
        migrations.AddField(
            model_name='prompt',
            name='max_output_tokens',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='prompt',
            name='system_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prompt',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
        ),
        migrations.AddField(
            model_name='prompt',
            name='template_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prompttestrun',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='prompts_app.prompt'),
        ),
        migrations.DeleteModel(
            name='PromptRoleMap',
        ),
        migrations.DeleteModel(
            name='PromptVersion',
        ),
    ]
