from django.db import models
from django.conf import settings
from jobs.models import Job
from users.models import ConsultantProfile

class PromptTemplate(models.Model):
    name = models.CharField(max_length=100)
    template = models.TextField(help_text="Use {job_description}, {consultant_bio}, {consultant_skills} as placeholders.")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Resume(models.Model):
    consultant = models.ForeignKey(ConsultantProfile, on_delete=models.CASCADE, related_name='generated_resumes')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='resumes')
    generated_content = models.TextField(help_text="Content generated by LLM")
    docx_file = models.FileField(upload_to='resumes/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Resume for {self.consultant.user.username} - {self.job.title}"
