# Generated by Django 5.2.11 on 2026-02-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='original_link',
            field=models.URLField(blank=True, help_text='Link to the original job posting', max_length=500),
        ),
    ]
