# Generated by Django 5.2.11 on 2026-02-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_original_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
    ]
