# Generated by Django 5.2.11 on 2026-02-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='original_link',
            field=models.URLField(help_text='Link to the original job posting', max_length=500),
        ),
    ]
