# Generated by Django 5.2.11 on 2026-02-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_company_alter_job_original_link'),
        ('users', '0006_marketingrole_consultantprofile_marketing_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='marketing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='users.marketingrole'),
        ),
    ]
