# Generated by Django 5.2.11 on 2026-02-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_marketing_role'),
        ('users', '0008_department_alter_employeeprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='marketing_role',
        ),
        migrations.AddField(
            model_name='job',
            name='marketing_roles',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='users.marketingrole'),
        ),
    ]
