# Generated by Django 5.2.11 on 2026-02-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_marketing_role_job_marketing_roles'),
        ('users', '0010_employeeprofile_can_manage_consultants'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Template Name', max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_marketing_roles', models.ManyToManyField(blank=True, to='users.marketingrole')),
            ],
        ),
    ]
