# Generated by Django 5.2.13 on 2026-04-28 21:15

import django.db.models.deletion
from django.db import migrations, models


def backfill_queue_entered_at(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    from django.utils import timezone

    now = timezone.now()
    Job.objects.filter(status="POOL", queue_entered_at__isnull=True).update(queue_entered_at=now)
    Job.objects.filter(status="OPEN", vet_approved_at__isnull=True).update(vet_approved_at=now)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0026_rawjob_classification_confidence_and_more'),
        ('jobs', '0016_backfill_stage_and_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidate_fit_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='data_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='gate_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='gate_status',
            field=models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('REVIEW', 'Needs Review'), ('BLOCKED', 'Blocked')], db_index=True, default='REVIEW', max_length=12),
        ),
        migrations.AddField(
            model_name='job',
            name='hard_gate_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='hard_gate_failures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='hard_gate_passed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='pipeline_reason_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='pipeline_reason_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='queue_entered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source_raw_job',
            field=models.ForeignKey(blank=True, help_text='Raw harvest source row used to create this pooled job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_jobs', to='harvest.rawjob'),
        ),
        migrations.AddField(
            model_name='job',
            name='trust_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vet_approved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vet_lane',
            field=models.CharField(choices=[('AUTO', 'Auto-Approve Lane'), ('HUMAN', 'Human Review Lane'), ('BLOCKED', 'Blocked Lane')], db_index=True, default='HUMAN', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='vet_priority_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_queue_entered_at, noop_reverse),
    ]
