# Generated by Django 5.2.13 on 2026-05-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_candidate_fit_score_job_data_quality_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='classified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, choices=[('software_dev', 'Software Development'), ('data_analytics', 'Data & Analytics'), ('devops_cloud', 'DevOps & Cloud'), ('security', 'Security & Cybersecurity'), ('it_support', 'IT Support & Help Desk'), ('qa_testing', 'QA & Testing'), ('systems_network', 'Systems & Network'), ('it_management', 'IT Management & Architecture'), ('healthcare_it', 'Healthcare IT'), ('management', 'Management & C-Suite'), ('sales', 'Sales & Business Development'), ('marketing', 'Marketing & Communications'), ('hr', 'Human Resources'), ('finance', 'Finance & Accounting'), ('operations', 'Operations & Logistics'), ('legal', 'Legal & Compliance'), ('customer_success', 'Customer Success'), ('design', 'Design & Creative'), ('admin', 'Administrative'), ('civil_eng', 'Civil & Construction'), ('healthcare', 'Healthcare & Clinical'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='department_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='job',
            name='department_source',
            field=models.CharField(blank=True, help_text='rules|embedding|llm|synced|manual', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='needs_reclassification',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.CharField(blank=True, help_text='APAC/EMEA/LATAM/Worldwide for multi-country roles', max_length=50),
        ),
    ]
