# Generated by Django 5.2.11 on 2026-02-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EduConsult', max_length=100)),
                ('site_tagline', models.CharField(blank=True, default='Connecting Experts with Opportunities', max_length=200)),
                ('logo_url', models.URLField(blank=True, help_text='External URL to logo image')),
                ('meta_description', models.TextField(blank=True, help_text='Default meta description for SEO')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('contact_email', models.EmailField(default='support@educonsult.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('enable_consultant_registration', models.BooleanField(default=True, help_text='Allow new consultants to register')),
                ('enable_job_applications', models.BooleanField(default=True, help_text='Allow consultants to apply for jobs')),
                ('enable_public_consultant_view', models.BooleanField(default=True, help_text='Allow guests to view consultant profiles')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='We are currently performing scheduled maintenance. Please check back later.')),
                ('session_timeout_minutes', models.IntegerField(default=60, help_text='Session expiry time in minutes')),
                ('max_upload_size_mb', models.IntegerField(default=5, help_text='Max file upload size in MB')),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('tos_url', models.URLField(blank=True, verbose_name='Terms of Service URL')),
                ('privacy_policy_url', models.URLField(blank=True, verbose_name='Privacy Policy URL')),
            ],
        ),
    ]
