# Generated by Django 5.2.11 on 2026-02-12 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        ('jobs', '0007_jobtemplate'),
        ('resumes', '0003_delete_resume_alter_resumedraft_unique_together'),
        ('users', '0010_employeeprofile_can_manage_consultants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField(blank=True, help_text='Encrypted OpenAI API key')),
                ('active_model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('system_prompt', models.TextField(blank=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('max_output_tokens', models.PositiveIntegerField(default=2000)),
                ('monthly_token_cap', models.PositiveIntegerField(default=0, help_text='0 means no cap')),
                ('generation_enabled', models.BooleanField(default=True)),
                ('auto_disable_on_cap', models.BooleanField(default=True)),
                ('data_pipelines_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.prompttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='LLMConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_model', models.CharField(max_length=100)),
                ('system_prompt', models.TextField(blank=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('max_output_tokens', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.llmconfig')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='resume_generation', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_input', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_output', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_total', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.consultantprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
