# Generated by Django 5.2.11 on 2026-02-13 07:58
# Dependency on prompts_app removed — prompts_app is no longer installed.
# The AddField operation already ran in production; 0024 drops the column.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_llmconfig_llmconfigversion_llmusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='active_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts_app.prompt'),
        ),
    ]
