# Generated by Django 5.2.11 on 2026-02-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_llmconfig_llmconfigversion_llmusagelog'),
        ('prompts_app', '0002_alter_promptversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='active_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts_app.prompt'),
        ),
    ]
