# Generated by Django 5.2.11 on 2026-02-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_llmconfig_active_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusagelog',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='user_prompt',
            field=models.TextField(blank=True),
        ),
    ]
