# Generated by Django 5.2.11 on 2026-02-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_llmusagelog_request_payload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmconfig',
            name='prompt_template',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='llmconfigversion',
            name='prompt_template',
        ),
        migrations.RemoveField(
            model_name='llmconfigversion',
            name='system_prompt',
        ),
    ]
