# Generated by Django 5.2.11 on 2026-04-04 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_enrich_on_create'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='job_auto_close_after_days',
            field=models.PositiveIntegerField(blank=True, help_text='If set, OPEN jobs older than this many days are closed automatically (daily task). Leave empty to disable.', null=True),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='job_auto_close_when_link_dead',
            field=models.BooleanField(default=False, help_text='If enabled, OPEN jobs whose original posting URL is no longer live are closed automatically.'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SUBMISSION', 'Submission'), ('INTERVIEW', 'Interview'), ('JOB', 'Job'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Relative path, e.g. /submissions/12/', max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'), models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_bd2d4b_idx')],
            },
        ),
    ]
