# Generated by Django 5.2.13 on 2026-05-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_platformconfig_color_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
