# Generated by Django 5.2.13 on 2026-05-10 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_dup_pending_context_processor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Per-request UUID; ties middleware rows to explicit log_audit_event calls.', max_length=36),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, help_text='Stable machine id, e.g. http.feature_flag_update or submissions.workflow.move', max_length=128),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='human_summary',
            field=models.TextField(blank=True, help_text='One-line plain-English description for dashboards and AI handoff.'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied'), ('partial', 'Partial'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='url_name',
            field=models.CharField(blank=True, help_text='URL pattern name from resolver, if known.', max_length=128),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='view_name',
            field=models.CharField(blank=True, help_text='Django resolver view callable name, if known.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp', 'event_code'], name='core_auditl_timesta_91a989_idx'),
        ),
    ]
