# Generated by Django 5.2.13 on 2026-04-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0006_raw_jobs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rawjob',
            new_name='harvest_raw_company_4ed860_idx',
            old_name='harvest_rawjob_company_platform_idx',
        ),
        migrations.RenameIndex(
            model_name='rawjob',
            new_name='harvest_raw_platfor_8faa80_idx',
            old_name='harvest_rawjob_platform_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='rawjob',
            new_name='harvest_raw_sync_st_edb2d5_idx',
            old_name='harvest_rawjob_sync_status_idx',
        ),
        migrations.RenameIndex(
            model_name='rawjob',
            new_name='harvest_raw_posted__8c1999_idx',
            old_name='harvest_rawjob_posted_date_idx',
        ),
        migrations.RenameIndex(
            model_name='rawjob',
            new_name='harvest_raw_employm_f29212_idx',
            old_name='harvest_rawjob_employment_type_idx',
        ),
        migrations.RenameIndex(
            model_name='rawjob',
            new_name='harvest_raw_locatio_553615_idx',
            old_name='harvest_rawjob_location_type_idx',
        ),
        migrations.RenameIndex(
            model_name='rawjob',
            new_name='harvest_raw_is_acti_4e8dab_idx',
            old_name='harvest_rawjob_is_active_idx',
        ),
    ]
