# Generated by Django 5.2.13 on 2026-04-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_company_type'),
        ('harvest', '0011_tighten_gem_join_url_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjob',
            name='benefits_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='clearance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='education_required',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('HS', 'High School'), ('ASSOCIATE', "Associate's"), ('BS', "Bachelor's"), ('MS', "Master's"), ('MBA', 'MBA'), ('PHD', 'PhD')], max_length=12),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='job_category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='languages_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='relocation_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='salary_equity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='signing_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='travel_required',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='visa_sponsorship',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='work_authorization',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='years_required',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='years_required_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['job_category'], name='harvest_raw_job_cat_55c939_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['education_required'], name='harvest_raw_educati_3988c6_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['visa_sponsorship'], name='harvest_raw_visa_sp_f1abe2_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['clearance_required'], name='harvest_raw_clearan_cb7764_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['quality_score'], name='harvest_raw_quality_df4f12_idx'),
        ),
    ]
