# Generated by Django 5.2.13 on 2026-04-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0015_platformconfig_delete_atsplatformpolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestrun',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='harvestrun',
            name='triggered_user',
        ),
        migrations.DeleteModel(
            name='HarvestedJob',
        ),
        migrations.DeleteModel(
            name='HarvestRun',
        ),
    ]
