# Generated by Django 5.2.13 on 2026-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0018_harvest_engine_config_pipeline_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='api_stagger_ms',
            field=models.PositiveIntegerField(default=100, help_text='Milliseconds between queuing tasks for JSON-API platforms (Greenhouse, Lever, Workday …). Lower = faster queue fill. Takes effect on next batch run.', verbose_name='API platform stagger (ms)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='min_hours_since_fetch',
            field=models.PositiveSmallIntegerField(default=6, help_text='Skip any company that was successfully fetched within this many hours. Set to 0 to force re-fetch everything every run. Takes effect on next batch run.', verbose_name='Min hours between re-fetches'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='scraper_stagger_ms',
            field=models.PositiveIntegerField(default=1500, help_text='Milliseconds between queuing tasks for HTML-scraper platforms (iCIMS, Taleo, Jobvite …). Keep ≥1000 to avoid hammering slow sites. Takes effect on next batch run.', verbose_name='Scraper platform stagger (ms)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='task_rate_limit',
            field=models.PositiveSmallIntegerField(default=6, help_text='Max fetch tasks each worker runs per minute. Total throughput = this × worker_concurrency. Applied immediately to running workers — no restart needed.', verbose_name='Tasks per worker per minute'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='task_soft_time_limit_secs',
            field=models.PositiveSmallIntegerField(default=480, help_text='A single company-fetch task that runs longer than this gets a graceful shutdown signal (marks run as PARTIAL). Hard kill fires 120s later.', verbose_name='Soft time limit (seconds)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='worker_concurrency',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many company-fetch tasks run in parallel per worker. Matches the --concurrency flag on the celery_harvest container. Rule of thumb: CPU count for CPU-heavy workloads, 2×CPU for I/O-heavy. Change HARVEST_CONCURRENCY in .env.production and restart celery_harvest to apply.', verbose_name='Worker concurrency'),
        ),
    ]
