# Generated by Django 5.2.13 on 2026-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_founding_year_company_funding_amount_and_more'),
        ('harvest', '0024_repair_has_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjob',
            name='company_founding_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='company_funding',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='company_industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='company_size',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='company_stage',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='department_normalized',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='encouraged_to_apply',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='job_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='shift_schedule',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['department_normalized'], name='harvest_raw_departm_33341a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['country'], name='harvest_raw_country_4b9fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['state'], name='harvest_raw_state_003029_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['years_required'], name='harvest_raw_years_r_cd911c_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['shift_schedule'], name='harvest_raw_shift_s_e4b957_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['company_industry'], name='harvest_raw_company_87f5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['company_size'], name='harvest_raw_company_2eeff2_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['company_founding_year'], name='harvest_raw_company_00290f_idx'),
        ),
    ]
