# Generated by Django 5.2.13 on 2026-04-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_employee_count_band_and_more'),
        ('harvest', '0025_rawjob_company_founding_year_rawjob_company_funding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjob',
            name='classification_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='classification_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='cleaning_version',
            field=models.CharField(blank=True, default='v2', max_length=20),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='clearance_level',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='company_employee_count_band',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='description_clean',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='description_raw_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='field_confidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='field_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='has_html_content',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='hours_hint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='licenses_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='normalized_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='resume_ready_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='schedule_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='shift_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='title_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='travel_pct_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='travel_pct_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='weekend_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['normalized_title'], name='harvest_raw_normali_27026f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['clearance_level'], name='harvest_raw_clearan_f4611a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['schedule_type'], name='harvest_raw_schedul_000ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['weekend_required'], name='harvest_raw_weekend_d6ec86_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['travel_pct_min'], name='harvest_raw_travel__083096_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['travel_pct_max'], name='harvest_raw_travel__294dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['company_employee_count_band'], name='harvest_raw_company_a8dfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['jd_quality_score'], name='harvest_raw_jd_qual_682adc_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['classification_confidence'], name='harvest_raw_classif_226a77_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['resume_ready_score'], name='harvest_raw_resume__00927b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['has_html_content'], name='harvest_raw_has_htm_531f58_idx'),
        ),
    ]
