# Generated by Django 5.2.13 on 2026-04-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvest", "0026_rawjob_classification_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvestengineconfig",
            name="resume_jd_min_chars",
            field=models.PositiveSmallIntegerField(
                default=400,
                help_text="Minimum cleaned JD character length required before a raw job is considered resume-usable.",
                verbose_name="Resume JD minimum characters",
            ),
        ),
        migrations.AddField(
            model_name="harvestengineconfig",
            name="resume_jd_min_classification_confidence",
            field=models.FloatField(
                default=0.35,
                help_text="Minimum classification confidence (0-1) required for resume-ready gating.",
                verbose_name="Resume JD minimum classification confidence",
            ),
        ),
        migrations.AddField(
            model_name="harvestengineconfig",
            name="resume_jd_min_words",
            field=models.PositiveSmallIntegerField(
                default=80,
                help_text="Minimum cleaned JD word count required before a raw job is considered resume-usable.",
                verbose_name="Resume JD minimum words",
            ),
        ),
    ]
