# Generated by Django 5.2.13 on 2026-05-02 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_employee_count_band_and_more'),
        ('harvest', '0030_rename_platformconfig_to_platformengineconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawJobDuplicatePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('EXACT', 'Exact Duplicate'), ('STRONG_MATCH', 'Strong Match'), ('URL_DUPLICATE', 'URL Duplicate'), ('REQUISITION', 'Requisition Duplicate'), ('NEAR_DUPLICATE', 'Near Duplicate'), ('LOCATION_VARIANT', 'Location Variant'), ('REPOST', 'Repost'), ('AGENCY_DUP', 'Agency Duplicate'), ('NOT_DUPLICATE', 'Not Duplicate')], db_index=True, max_length=32)),
                ('similarity', models.FloatField(default=0.0)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending Review'), ('MERGED', 'Merged'), ('DISMISSED', 'Keep Both'), ('CONFIRMED', 'Confirmed Duplicate')], db_index=True, default='PENDING', max_length=16)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='rawjob',
            name='harvest_raw_origurl_idx',
        ),
        migrations.AlterField(
            model_name='rawjob',
            name='original_url',
            field=models.URLField(blank=True, db_index=True, max_length=1024),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['education_required'], name='harvest_raw_educati_3988c6_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['quality_score'], name='harvest_raw_quality_df4f12_idx'),
        ),
        migrations.AddField(
            model_name='rawjobduplicatepair',
            name='duplicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_as_secondary', to='harvest.rawjob'),
        ),
        migrations.AddField(
            model_name='rawjobduplicatepair',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_as_primary', to='harvest.rawjob'),
        ),
        migrations.AddField(
            model_name='rawjobduplicatepair',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rawjobduplicatepair',
            index=models.Index(fields=['resolution', '-detected_at'], name='dup_res_detected_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjobduplicatepair',
            index=models.Index(fields=['label', '-detected_at'], name='dup_label_detected_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawjobduplicatepair',
            unique_together={('primary', 'duplicate')},
        ),
    ]
