# Generated by Django 5.2.13 on 2026-05-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0031_add_rawjob_duplicate_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjob',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='rawjob',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('DUPLICATE', 'Duplicate')], default='PENDING', max_length=16),
        ),
    ]
