# Generated by Django 5.2.13 on 2026-05-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0032_add_content_hash_duplicate_syncstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchbatch',
            name='audit_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Structured harvest audit: queue snapshot + completion metrics (UI + grep-friendly logs).'),
        ),
    ]
