# Generated by Django 5.2.13 on 2026-05-04 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0033_fetchbatch_audit_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestOpsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('detect_platforms', 'Detect platforms'), ('backfill_jd', 'Backfill JD'), ('validate_urls', 'Validate live links'), ('sync_pool', 'Sync to vet pool'), ('cleanup', 'Cleanup harvested'), ('classify', 'Classify raw jobs')], db_index=True, max_length=64)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='RUNNING', max_length=16)),
                ('audit_payload', models.JSONField(blank=True, default=dict, help_text='Structured audit: queue snapshot + completion metrics (same shape spirit as FetchBatch).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_ops_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Harvest ops run',
                'verbose_name_plural': 'Harvest ops runs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='harvest_har_created_c18f22_idx')],
            },
        ),
    ]
