# Generated by Django 5.2.13 on 2026-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0035_rawjob_vendor_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfetchrun',
            name='issue_code',
            field=models.CharField(blank=True, choices=[('', 'None'), ('PORTAL_DOWN', 'Portal Down / Unreachable'), ('PORTAL_BLOCKED', 'Anti-bot / Access Blocked'), ('NO_JOBS_RETURNED', 'Portal reachable but returned 0 jobs'), ('NO_ACTIVE_TENANT', 'Tenant has no active jobs'), ('PARSE_FAILED', 'Response received but parse failed'), ('TENANT_INVALID', 'Tenant ID missing or invalid'), ('RATE_LIMITED', 'Rate limited by platform'), ('FETCH_TIMEOUT', 'Fetch timed out mid-crawl'), ('PARTIAL_RESULTS', 'Partial results (e.g. timeout after some pages)')], default='', help_text='Fine-grained issue code for analytics (supplements error_type).', max_length=20),
        ),
        migrations.AddField(
            model_name='jobboardplatform',
            name='support_tier',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('experimental', 'Experimental'), ('unsupported', 'Unsupported')], default='healthy', help_text='Operational health tier. UNSUPPORTED = excluded from normal harvest rotation.', max_length=16),
        ),
        migrations.AlterField(
            model_name='companyfetchrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('EMPTY', 'Empty (0 jobs)'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10),
        ),
    ]
