# Generated by Django 5.2.13 on 2026-05-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0036_board_analytics_support_tier_empty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfetchrun',
            name='field_presence',
            field=models.JSONField(blank=True, default=dict, help_text='Per-field counts of jobs that had the field populated at harvest time. Keys: jd, requirements, responsibilities, department, geo, salary, employment_type, education, experience_level.'),
        ),
        migrations.AddField(
            model_name='companyfetchrun',
            name='jobs_detail_fetched',
            field=models.PositiveIntegerField(default=0, help_text='Number of jobs for which a detail page / second HTTP call was fetched.'),
        ),
    ]
