# Generated by Django 5.2.13 on 2026-05-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0037_companyfetchrun_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjob',
            name='sync_skip_reason',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Gate reason code when sync_status=SKIPPED. Mirrors jobs.gating reason codes: INACTIVE_POSTING, JD_TOO_WEAK, PLATFORM_MISMATCH, DUPLICATE_RISK, COMPANY_UNRESOLVED, etc.', max_length=32),
        ),
    ]
