# Generated by Django 5.2.13 on 2026-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_add_possible_duplicate_needs_review'),
        ('harvest', '0038_rawjob_sync_skip_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjob',
            name='domain_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='job_domain',
            field=models.CharField(blank=True, db_index=True, help_text='MarketingRole slug auto-assigned by domain classification engine', max_length=120),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['job_domain'], name='harvest_raw_job_dom_955da2_idx'),
        ),
    ]
