# Generated by Django 5.2.13 on 2026-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_add_possible_duplicate_needs_review'),
        ('harvest', '0040_rawjob_job_domain_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(blank=True, max_length=512)),
                ('normalized_text', models.CharField(db_index=True, max_length=512, unique=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=128)),
                ('region_code', models.CharField(blank=True, max_length=16)),
                ('region_name', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(blank=True, db_index=True, max_length=32)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('provider_place_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('RESOLVED', 'Resolved'), ('UNKNOWN', 'Unknown'), ('FAILED', 'Failed'), ('RATE_LIMITED', 'Rate limited'), ('DISABLED', 'Provider disabled')], db_index=True, default='UNKNOWN', max_length=16)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('looked_up_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['normalized_text'],
            },
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='geocoding_cache_enabled',
            field=models.BooleanField(default=True, help_text='Read/write normalized location resolutions before any provider lookup.', verbose_name='Location cache enabled'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='geocoding_monthly_limit',
            field=models.PositiveIntegerField(default=80000, help_text='Hard stop for provider requests per calendar month. Default 80k to stay below 100k free-tier claims.', verbose_name='Provider monthly hard limit'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='geocoding_provider',
            field=models.CharField(choices=[('none', 'None'), ('mapbox', 'Mapbox'), ('google', 'Google')], default='none', help_text='External fallback provider. Token must come from environment, never the database.', max_length=16, verbose_name='Geocoding provider'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='geocoding_provider_enabled',
            field=models.BooleanField(default=False, help_text='Allow external geocoding only for unresolved unique locations.', verbose_name='Provider fallback enabled'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='process_unknown_country_with_target_domain',
            field=models.BooleanField(default=True, help_text='Keep unknown-location jobs in review unless the title/domain strongly matches a target IT/engineering route.', verbose_name='Process unknown country if domain is target'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='target_countries',
            field=models.JSONField(blank=True, default=list, help_text='ISO country codes that should receive full processing. Empty uses US, IN, CA, GB, AU.', verbose_name='Target countries'),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='country_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='country_source',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='is_priority',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='last_scope_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='scope_reason',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='scope_status',
            field=models.CharField(choices=[('UNSCOPED', 'Unscoped'), ('PRIORITY_TARGET', 'Priority target'), ('REVIEW_UNKNOWN_COUNTRY', 'Review unknown country'), ('COLD_NON_TARGET_COUNTRY', 'Cold non-target country'), ('COLD_NO_LOCATION', 'Cold no location')], db_index=True, default='UNSCOPED', max_length=32),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['country_code'], name='harvest_raw_country_9fe555_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['scope_status'], name='harvest_raw_scope_s_0a35b8_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['is_priority'], name='harvest_raw_is_prio_35cb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['is_priority', '-fetched_at'], name='raw_priority_fetched_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['scope_status', '-fetched_at'], name='raw_scope_fetched_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcache',
            index=models.Index(fields=['country_code', 'status'], name='loc_cache_country_status_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcache',
            index=models.Index(fields=['source', 'status'], name='loc_cache_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcache',
            index=models.Index(fields=['provider', 'created_at'], name='loc_cache_provider_created_idx'),
        ),
    ]
