# Generated by Django 5.2.13 on 2026-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0041_locationcache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestengineconfig',
            name='geocoding_provider_token',
            field=models.CharField(blank=True, default='', help_text='Optional API token stored in DB so it can be rotated from the GUI. When blank, the resolver falls back to MAPBOX_ACCESS_TOKEN / GOOGLE_MAPS_API_KEY environment variables. Env var is the more secure pattern; DB storage exists for convenience.', max_length=512, verbose_name='Geocoding provider token (DB)'),
        ),
    ]
