# Generated by Django 5.2.13 on 2026-05-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0043_rawjob_location_candidates_country_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestopsrun',
            name='progress_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='harvestopsrun',
            name='progress_message',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='harvestopsrun',
            name='progress_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='harvestopsrun',
            name='operation',
            field=models.CharField(choices=[('detect_platforms', 'Detect platforms'), ('backfill_jd', 'Backfill JD'), ('validate_urls', 'Validate live links'), ('sync_pool', 'Sync to vet pool'), ('cleanup', 'Cleanup harvested'), ('classify', 'Classify raw jobs'), ('classify_domains', 'Classify domains'), ('evaluate_scope', 'Evaluate RawJob scope'), ('backfill_roles', 'Backfill marketing roles'), ('refetch_locations', 'Refetch ambiguous locations'), ('backfill_enrichment', 'Backfill enrichment')], db_index=True, max_length=64),
        ),
    ]
