# Generated by Django 5.2.13 on 2026-05-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0045_harvestopsrun_llm_classify_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawJobPayloadSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_slug', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('payload_kind', models.CharField(choices=[('list', 'List payload'), ('detail', 'Detail payload'), ('jsonld', 'JSON-LD'), ('html', 'Raw HTML'), ('api_response', 'API response'), ('backfill', 'Legacy backfill'), ('failure', 'Failure metadata')], db_index=True, default='api_response', max_length=16)),
                ('schema_version', models.CharField(blank=True, default='source-v1', max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('raw_html_gzip', models.BinaryField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('payload_size_bytes', models.PositiveIntegerField(default=0)),
                ('raw_html_size_bytes', models.PositiveIntegerField(default=0)),
                ('redaction_version', models.CharField(blank=True, default='v1', max_length=16)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('is_failure', models.BooleanField(db_index=True, default=False)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fetch_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payload_snapshots', to='harvest.fetchbatch')),
                ('raw_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload_snapshots', to='harvest.rawjob')),
            ],
            options={
                'verbose_name': 'Raw Job Payload Snapshot',
                'verbose_name_plural': 'Raw Job Payload Snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['raw_job', '-captured_at'], name='raw_payload_job_time_idx'), models.Index(fields=['platform_slug', 'payload_kind'], name='raw_payload_platform_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('raw_job', 'payload_kind', 'content_hash'), name='uniq_rawjob_payload_kind_hash')],
            },
        ),
    ]
