# Generated by Django 5.2.13 on 2026-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0052_harvestopsrun_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='backfill_jd_include_cold',
            field=models.BooleanField(default=False, help_text='When False (default) only PRIORITY (target-country) jobs get JD backfill. Enable to also fetch descriptions for COLD and REVIEW_* jobs — useful after expanding target_countries or for full-coverage audits.', verbose_name='Include COLD / REVIEW jobs in JD backfill'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='backfill_jd_reset_locks',
            field=models.BooleanField(default=True, help_text='When True the Backfill JD button automatically clears locks older than BACKFILL_LOCK_STALE_MINUTES before claiming rows. Prevents stale worker-crash locks from silently blocking re-runs.', verbose_name='Reset stale JD locks by default'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='backfill_jd_workers',
            field=models.PositiveSmallIntegerField(default=4, help_text='Concurrent chunk-worker threads for description backfill. Hard-capped at 8 internally. Keep ≤ half your Celery pool size to avoid starving other tasks. Takes effect on next Backfill JD run.', verbose_name='JD backfill parallel workers'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='classify_chunk_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum RawJobs processed per classify run. Set >0 to prevent timeouts on very large backlogs (e.g. 50000). Remaining rows are processed on the next scheduled run. 0 means process everything in one shot (original behaviour).', verbose_name='Classify chunk limit (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='classify_lock_ttl_minutes',
            field=models.PositiveSmallIntegerField(default=180, help_text='How long the classify singleton lock is held. If the worker crashes the lock self-expires after this many minutes. Default 180 (3 h). Staff can also clear it manually via the Force Unlock button.', verbose_name='Classify lock TTL (minutes)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='cleanup_inactive_age_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Inactive rows older than this are purged by Phase 3 of cleanup. Default 7 days. Rows that are inactive+PENDING are always purged immediately (Phase 2) regardless of age.', verbose_name='Cleanup — inactive row max age (days)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='cleanup_pending_safe_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Phase 2 only deletes inactive+PENDING rows fetched more than this many minutes ago. Prevents a race where cleanup deletes a row that a sync task just picked up. Default 10 minutes.', verbose_name='Cleanup — PENDING safe buffer (minutes)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='detect_batch_size',
            field=models.PositiveSmallIntegerField(default=200, help_text='How many companies are processed per Run Detection task. Takes effect on next Run Detection trigger.', verbose_name='Detection batch size'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='retry_failed_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Retry Failed re-queues company fetch tasks that FAILED within this many days. Default 7. Increase to recover from longer outages.', verbose_name='Retry failed — look-back window (days)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='validate_links_include_synced',
            field=models.BooleanField(default=False, help_text='When False (default) the Validate Live Links button only checks jobs still in PENDING sync state. Enable to also re-validate jobs already promoted to the pool — catches URLs that expired after sync.', verbose_name='Validate links for SYNCED pool jobs too'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='validate_links_recent_hours',
            field=models.PositiveSmallIntegerField(default=168, help_text='Only check jobs fetched within this many hours. Default 168 (7 days). Set 0 to validate all active jobs regardless of age.', verbose_name='Validate links — recent hours window'),
        ),
    ]
