# Generated by Django 5.2.13 on 2026-05-12 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


ROLE_CATEGORIES = [
    ("devops", "DevOps / Cloud / Infrastructure", 10, [
        "devops engineer", "dev ops engineer", "site reliability engineer", "sre",
        "platform engineer", "cloud engineer", "infrastructure engineer",
        "devsecops engineer", "mlops engineer", "cloud architect",
        "solutions architect", "reliability engineer", "deployment engineer",
        "release engineer", "build engineer", "systems reliability engineer",
        "infrastructure architect", "cloud operations engineer",
        "kubernetes engineer", "cloud platform engineer", "infra engineer",
        "cloud devops", "devops lead", "platform infrastructure engineer",
        "cloud infrastructure engineer", "devops architect",
    ]),
    ("software", "Software Engineering / Full Stack / Backend / Frontend", 20, [
        "software engineer", "software developer", "full stack engineer",
        "full stack developer", "fullstack engineer", "backend engineer",
        "backend developer", "frontend engineer", "frontend developer",
        "web developer", "web engineer", "mobile engineer", "ios engineer",
        "ios developer", "android engineer", "android developer",
        "embedded engineer", "firmware engineer", "systems engineer",
        "systems developer", "application engineer", "application developer",
        "sde", "swe", "software development engineer", "api engineer",
        "distributed systems engineer", "founding engineer", "staff engineer",
        "principal engineer", "platform software engineer",
        "full stack software engineer", "software architect",
    ]),
    ("data", "Data Engineering / Analytics / BI", 30, [
        "data engineer", "data analyst", "analytics engineer",
        "business intelligence developer", "bi developer", "bi engineer",
        "bi analyst", "data architect", "etl engineer", "etl developer",
        "pipeline engineer", "analytics developer", "reporting engineer",
        "data platform engineer", "data infrastructure engineer",
        "dataops engineer", "data operations engineer", "data engineering lead",
    ]),
    ("ai_ml", "AI / ML / Data Science", 40, [
        "machine learning engineer", "ml engineer", "ai engineer",
        "data scientist", "deep learning engineer", "nlp engineer",
        "computer vision engineer", "research scientist", "applied scientist",
        "applied ml engineer", "research engineer", "ai researcher",
        "ml researcher", "generative ai engineer", "llm engineer",
        "ai platform engineer", "recommendation systems engineer",
        "artificial intelligence engineer", "machine learning scientist",
        "applied research scientist", "ml platform engineer",
    ]),
    ("security", "Security / InfoSec / Network", 50, [
        "security engineer", "cybersecurity engineer", "information security engineer",
        "infosec engineer", "network engineer", "penetration tester", "pen tester",
        "soc analyst", "cloud security engineer", "application security engineer",
        "appsec engineer", "security architect", "security operations engineer",
        "network architect", "security analyst", "threat analyst",
        "vulnerability engineer", "identity engineer", "devsecops engineer",
        "cloud security architect", "network security engineer",
    ]),
    ("qa", "QA / SDET / Test Automation", 60, [
        "qa engineer", "quality engineer", "software test engineer", "sdet",
        "test automation engineer", "quality assurance engineer",
        "automation test engineer", "performance engineer",
        "load testing engineer", "software quality engineer",
        "test infrastructure engineer", "qa automation engineer",
    ]),
    ("product_tech", "Technical Product / Program / Architecture", 70, [
        "technical program manager", "tpm", "engineering manager",
        "technical lead", "tech lead", "technical architect",
        "software architect", "solution architect", "principal architect",
        "chief architect", "vp of engineering", "director of engineering",
        "head of engineering", "staff tpm", "technical product manager",
        "engineering director", "platform architect", "group engineering manager",
    ]),
]

HARD_NEGATIVES = [
    "nurse practitioner", "registered nurse", "licensed practical nurse",
    "licensed vocational nurse", "licensed clinical social worker",
    "physician assistant", "medical doctor", "pharmacist", "physical therapist",
    "occupational therapist", "speech therapist", "dental assistant",
    "dental hygienist", "dental technician", "veterinarian", "vet technician",
    "certified nursing assistant", "medical assistant", "radiologic technologist",
    "respiratory therapist", "surgical technician", "cashier", "store associate",
    "retail associate", "store manager", "retail manager", "store supervisor",
    "retail supervisor", "warehouse associate", "warehouse worker",
    "warehouse supervisor", "forklift operator", "material handler",
    "picker packer", "delivery driver", "truck driver", "cdl driver", "courier",
    "food service worker", "line cook", "prep cook", "sous chef",
    "executive chef", "pastry chef", "dishwasher", "barista", "server",
    "bartender", "host hostess", "housekeeper", "custodian", "janitor",
    "groundskeeper", "laundry attendant", "sales representative",
    "inside sales representative", "outside sales representative",
    "account executive sales", "sales account manager", "territory sales manager",
    "sales development representative", "business development representative",
    "bdr sales", "sdr sales", "technical recruiter",
    "talent acquisition specialist", "corporate recruiter", "hr generalist",
    "human resources manager", "hr business partner", "payroll specialist",
    "benefits administrator", "compensation analyst", "paralegal",
    "legal secretary", "contracts administrator", "marketing coordinator",
    "content writer", "copywriter", "technical writer", "graphic designer",
    "social media manager", "brand manager", "event coordinator",
    "administrative assistant", "receptionist", "executive assistant",
    "office manager", "customer service representative", "call center agent",
    "customer support specialist",
]

PLATFORM_DEFAULTS = {
    "workday": (True, 10),
    "greenhouse": (True, 10),
    "lever": (True, 10),
    "ashby": (True, 10),
    "smartrecruiters": (True, 10),
    "icims": (True, 5),
    "taleo": (False, 3),
    "ultipro": (False, 3),
    "ukg": (False, 3),
    "html_scrape": (False, 2),
}


def seed_selective_filter(apps, schema_editor):
    HarvestRoleCategory = apps.get_model("harvest", "HarvestRoleCategory")
    HarvestEngineConfig = apps.get_model("harvest", "HarvestEngineConfig")
    JobBoardPlatform = apps.get_model("harvest", "JobBoardPlatform")

    for slug, name, priority, phrases in ROLE_CATEGORIES:
        HarvestRoleCategory.objects.update_or_create(
            slug=slug,
            defaults={
                "name": name,
                "priority": priority,
                "is_active": True,
                "include_phrases": phrases,
                "exclude_phrases": [],
            },
        )

    cfg, _ = HarvestEngineConfig.objects.get_or_create(pk=1)
    if not cfg.hard_negative_phrases:
        cfg.hard_negative_phrases = HARD_NEGATIVES
        cfg.save(update_fields=["hard_negative_phrases", "updated_at"])

    for slug, (title_in_list, budget) in PLATFORM_DEFAULTS.items():
        JobBoardPlatform.objects.filter(slug=slug).update(
            title_in_list=title_in_list,
            unknown_jd_budget_per_run=budget,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_add_possible_duplicate_needs_review'),
        ('harvest', '0053_harvestengineconfig_helptext_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestFilterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('category_data', models.JSONField()),
                ('phrase_hash', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Harvest filter snapshot',
                'verbose_name_plural': 'Harvest filter snapshots',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRoleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('include_phrases', models.JSONField(default=list)),
                ('exclude_phrases', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Harvest role category',
                'verbose_name_plural': 'Harvest role categories',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HarvestSkippedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('platform_slug', models.CharField(max_length=64)),
                ('job_title', models.CharField(max_length=512)),
                ('job_external_id', models.CharField(blank=True, max_length=256)),
                ('department', models.CharField(blank=True, max_length=256)),
                ('filter_decision', models.CharField(max_length=16)),
                ('filter_reason', models.CharField(max_length=512)),
                ('matched_negative', models.CharField(blank=True, max_length=256)),
                ('snapshot_id', models.UUIDField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
                ('is_sampled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Harvest skipped title',
                'verbose_name_plural': 'Harvest skipped titles',
                'ordering': ['-skipped_at'],
            },
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='consecutive_zero_tech_fetches',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='custom_include_phrases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='skip_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='skip_in_selective_harvest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='zero_tech_last_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='cold_no_match_sample_rate_pct',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='filter_audit_mode',
            field=models.BooleanField(default=True, help_text='When True, classify and audit decisions without skipping JD fetch/backfill.', verbose_name='Selective filter audit mode'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='hard_negative_phrases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='selective_filter_enabled',
            field=models.BooleanField(default=False, help_text='Master switch. When False, harvest keeps the existing full-storage behavior.', verbose_name='Selective role filter enabled'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='zero_tech_skip_ttl_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='zero_tech_threshold',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='jobboardplatform',
            name='title_in_list',
            field=models.BooleanField(default=False, help_text='True when the list endpoint exposes enough title data for selective role filtering before JD fetch.'),
        ),
        migrations.AddField(
            model_name='jobboardplatform',
            name='unknown_jd_budget_per_run',
            field=models.PositiveSmallIntegerField(default=2, help_text='Max UNKNOWN title decisions per company run that may continue to JD fetch in selective harvest.'),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='filter_decision',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='filter_reason',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='filter_snapshot_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='is_cold',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_fetch_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='list_payload_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='role_category',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['filter_decision'], name='harvest_raw_filter__2fd28c_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjob',
            index=models.Index(fields=['is_cold'], name='harvest_raw_is_cold_7560fe_idx'),
        ),
        migrations.AddField(
            model_name='harvestfiltersnapshot',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_snapshots', to='harvest.fetchbatch'),
        ),
        migrations.AddField(
            model_name='harvestskippedtitle',
            name='raw_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skip_log', to='harvest.rawjob'),
        ),
        migrations.AddIndex(
            model_name='harvestskippedtitle',
            index=models.Index(fields=['skipped_at'], name='harvest_har_skipped_87751c_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestskippedtitle',
            index=models.Index(fields=['platform_slug'], name='harvest_har_platfor_873e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestskippedtitle',
            index=models.Index(fields=['filter_decision'], name='harvest_har_filter__9c4164_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestskippedtitle',
            index=models.Index(fields=['is_sampled'], name='harvest_har_is_samp_5131da_idx'),
        ),
        migrations.RunPython(seed_selective_filter, migrations.RunPython.noop),
    ]
