# Generated by Django 5.2.13 on 2026-05-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0054_harvestfiltersnapshot_harvestrolecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='api_stagger_ms',
            field=models.PositiveIntegerField(default=1000, help_text='Milliseconds between queuing tasks for JSON-API platforms (Greenhouse, Lever, Workday …). Lower = faster queue fill. Takes effect on next batch run.', verbose_name='API platform stagger (ms)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='backfill_jd_workers',
            field=models.PositiveSmallIntegerField(default=1, help_text='Concurrent chunk-worker threads for description backfill. Hard-capped at 1 internally on this deployment to protect web uptime.', verbose_name='JD backfill parallel workers'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='full_fetch_cooldown_minutes',
            field=models.PositiveSmallIntegerField(default=360, help_text='Minimum minutes between two Full Crawl runs. Enforced both in the UI and in the task via a cache key so direct API calls also respect the limit. Default 120 (2 h).', verbose_name='Full fetch cooldown (minutes)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='scraper_stagger_ms',
            field=models.PositiveIntegerField(default=5000, help_text='Milliseconds between queuing tasks for HTML-scraper platforms (iCIMS, Taleo, Jobvite …). Keep ≥1000 to avoid hammering slow sites. Takes effect on next batch run.', verbose_name='Scraper platform stagger (ms)'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='task_rate_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='Max fetch tasks each worker runs per minute. Total throughput = this × worker_concurrency. Applied immediately to running workers — no restart needed.', verbose_name='Tasks per worker per minute'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='worker_concurrency',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many company-fetch tasks run in parallel per worker. Matches the --concurrency flag on the celery_harvest container. Rule of thumb: CPU count for CPU-heavy workloads, 2×CPU for I/O-heavy. Change HARVEST_CONCURRENCY in .env.production and restart celery_harvest to apply.', verbose_name='Worker concurrency'),
        ),
    ]
