# Generated by Django 5.2.13 on 2026-05-14 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0056_rawjob_test_run_batch_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyplatformlabel',
            name='historical_ambiguous_count',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative AMBIGUOUS title-gate decisions for this company.'),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='historical_confirmed_count',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative CONFIRMED JD-gate decisions for this company.'),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='historical_hard_no_count',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative HARD_NO title-gate decisions for this company.'),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='historical_hard_yes_count',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative HARD_YES title-gate decisions for this company.'),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='historical_rejected_count',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative REJECTED JD-gate decisions for this company.'),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='jd_gate_threshold_override',
            field=models.FloatField(blank=True, help_text='Per-company JD gate confidence threshold override. NULL = use global HarvestEngineConfig value. Set lower (e.g. 0.50) for high-yield companies; higher for low-yield.', null=True),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='last_fetch_offset',
            field=models.PositiveIntegerField(default=0, help_text='Pagination checkpoint for incremental harvests. Stores the page offset where the last run stopped (e.g. after a timeout). Next run resumes from here. Reset to 0 on successful completion.'),
        ),
        migrations.AddField(
            model_name='companyplatformlabel',
            name='last_hit_rate_computed_at',
            field=models.DateTimeField(blank=True, help_text='When hit-rate counters were last updated.', null=True),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='jd_gate_audit_mode',
            field=models.BooleanField(default=True, help_text='When True: gate runs and records decisions (jd_gate_decision, jd_gate_reason) but does NOT suppress any jobs. Use this for 2–4 weeks to tune thresholds. Set False only after validating false-negative rate.', verbose_name='JD gate — audit mode (no suppression)'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='jd_gate_batch_size',
            field=models.PositiveSmallIntegerField(default=20, help_text='Jobs per LLM API call in JD gate. 20 is the sweet spot for cost vs latency.', verbose_name='JD gate — LLM batch size'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='jd_gate_confidence_threshold',
            field=models.FloatField(default=0.65, help_text='Min LLM confidence to enforce a YES/NO decision. Below this → UNCERTAIN (human review queue, ~2–3% of cases). Range 0.0–1.0. Default 0.65.', verbose_name='JD gate — confidence threshold'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='jd_gate_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for the JD relevance gate. Safe to deploy with False — does nothing. Enable jd_gate_audit_mode first to tune thresholds before enforcement.', verbose_name='JD content gate enabled (Tier 2)'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='jd_gate_model',
            field=models.CharField(default='gpt-4o-mini', help_text='OpenAI model for JD content gate. gpt-4o-mini is cheapest/fastest (~$0.001 per 20 jobs).', max_length=64, verbose_name='JD gate — LLM model'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='jd_gate_scope',
            field=models.CharField(choices=[('ambiguous_only', 'AMBIGUOUS titles only (safest — recommended start)'), ('all_possible', 'AMBIGUOUS + COLD-with-tech-signal (catch more false negatives)'), ('all_non_hard_no', 'Everything except HARD_NO (maximum accuracy, highest cost)')], default='ambiguous_only', help_text="Which jobs go through the Tier-2 JD content gate. Start with 'ambiguous_only' to validate, then expand scope.", max_length=32, verbose_name='JD gate — scope'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='jd_gate_snippet_chars',
            field=models.PositiveSmallIntegerField(default=800, help_text='Max chars of clean JD text sent to the LLM gate per job. 800 chars (~130 words) is enough to identify tech vs non-tech reliably. Increase for borderline roles; decrease to reduce token cost.', verbose_name='JD gate — snippet length (chars)'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='title_hard_yes_confidence',
            field=models.FloatField(default=0.8, help_text='Min phrase-match confidence to classify a title as HARD_YES (skips JD gate, goes straight to backfill). Below this threshold → AMBIGUOUS (sent to Tier-2 JD gate). Range 0.0–1.0. Default 0.80.', verbose_name='Title gate — HARD_YES confidence threshold'),
        ),
        migrations.AddField(
            model_name='jobboardplatform',
            name='list_has_description',
            field=models.BooleanField(default=False, help_text='True when the list endpoint returns job description text (e.g. Lever, Ashby, Greenhouse). Enables Tier-2 JD gate with ZERO extra HTTP calls — snippet is extracted from the list payload.'),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_gate_category',
            field=models.CharField(blank=True, help_text='Tech-category hint from JD gate LLM (e.g. devops, mlops). Pre-hints enrichment.', max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_gate_confidence',
            field=models.FloatField(blank=True, help_text='0.0–1.0 LLM confidence score from Tier-2 JD gate.', null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_gate_decision',
            field=models.CharField(blank=True, db_index=True, help_text='CONFIRMED | REJECTED | UNCERTAIN | SKIPPED | PENDING — Tier-2 LLM content gate.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_gate_model',
            field=models.CharField(blank=True, help_text='LLM model used for JD gate (e.g. gpt-4o-mini).', max_length=64),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_gate_ran_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the JD content gate was last evaluated for this job.', null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_gate_reason',
            field=models.TextField(blank=True, help_text='LLM-provided one-sentence reason for the gate decision (for audit).'),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='jd_gate_snippet',
            field=models.TextField(blank=True, help_text='First 800 chars of clean JD text used for the gate decision (for audit/debug).'),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='title_gate_confidence',
            field=models.FloatField(blank=True, help_text='0.0–1.0 phrase-match confidence score from Tier-1 title gate.', null=True),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='title_gate_decision',
            field=models.CharField(blank=True, db_index=True, help_text='HARD_YES | HARD_NO | AMBIGUOUS — output of confidence-aware title gate (Tier 1).', max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='HarvestPriorityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_slug', models.CharField(db_index=True, help_text="MarketingRole slug we're actively prioritizing (e.g. 'devops-sre', 'mlops-engineer').", max_length=120)),
                ('priority_boost', models.PositiveSmallIntegerField(default=5, help_text='1 = highest priority, 10 = lowest. Jobs matching this role jump the backfill queue.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = no expiry. Set a date to auto-expire the priority signal.', null=True)),
                ('notes', models.TextField(blank=True, help_text="e.g. 'Client X needs 3 engineers by June 2026'.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Harvest Priority Role',
                'verbose_name_plural': 'Harvest Priority Roles',
                'ordering': ['priority_boost', 'role_slug'],
            },
        ),
    ]
