# Generated by Django 5.2.13 on 2026-05-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0058_set_list_has_description_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestengineconfig',
            name='pre_storage_filter_enabled',
            field=models.BooleanField(default=False, help_text='When True, HARD_NO titles (NO_MATCH or COLD with confidence < 0.2) are dropped BEFORE writing to DB — only relevant jobs are ever stored. Requires selective_filter_enabled=True and filter_audit_mode=False. Enable only after verifying false-negative rate in audit mode.', verbose_name='Pre-storage filter (selective fetch)'),
        ),
    ]
