# Generated by Django 5.2.14 on 2026-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0062_vetgateconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetgateconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
