# Generated by Django 5.2.11 on 2026-02-11 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_marketing_role'),
        ('resumes', '0001_initial'),
        ('users', '0008_department_alter_employeeprofile_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job',
        ),
        migrations.CreateModel(
            name='ResumeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Generated resume markdown')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DRAFT', 'Draft'), ('FINAL', 'Final'), ('ERROR', 'Error')], default='PROCESSING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if generation failed')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Total tokens consumed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_drafts', to='users.consultantprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drafts', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_drafts', to='jobs.job')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
