# Generated by Django 5.2.11 on 2026-02-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resume_consultant_remove_resume_job_and_more'),
        ('submissions', '0002_alter_applicationsubmission_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AlterUniqueTogether(
            name='resumedraft',
            unique_together={('consultant', 'job', 'version')},
        ),
    ]
