# Generated by Django 5.2.11 on 2026-02-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_delete_resume_alter_resumedraft_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedraft',
            name='llm_input_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='llm_system_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='llm_user_prompt',
            field=models.TextField(blank=True),
        ),
    ]
