# Generated by Django 5.2.11 on 2026-02-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_llmconfig_prompt_template_and_more'),
        ('resumes', '0004_resumedraft_llm_input_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedraft',
            name='prompt_template',
        ),
        migrations.DeleteModel(
            name='PromptTemplate',
        ),
    ]
