# Generated by Django 5.2.11 on 2026-02-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_remove_resumedraft_prompt_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedraft',
            name='llm_request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
