# Generated by Django 5.2.11 on 2026-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_llminputpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedraft',
            name='ats_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumedraft',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('DRAFT', 'Draft'), ('REVIEW', 'Review Required'), ('FINAL', 'Final'), ('ERROR', 'Error')], default='PROCESSING', max_length=20),
        ),
    ]
