# Generated by Django 5.2.11 on 2026-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_resumetemplate'),
        ('users', '0011_consultantprofile_base_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='marketing_roles',
            field=models.ManyToManyField(blank=True, related_name='resume_templates', to='users.marketingrole'),
        ),
    ]
