# Generated by Django 5.2.11 on 2026-02-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_resumetemplate_marketing_roles'),
        ('users', '0011_consultantprofile_base_resume_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplatePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketing_roles', models.ManyToManyField(blank=True, related_name='template_packs', to='users.marketingrole')),
                ('templates', models.ManyToManyField(blank=True, related_name='packs', to='resumes.resumetemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
