# Generated by Django 5.2.13 on 2026-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0017_resume_template_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedraft',
            name='auto_generated',
            field=models.BooleanField(db_index=True, default=False, help_text='True when created by the auto_generate_for_new_jobs pipeline (not manual).'),
        ),
    ]
