# Generated by Django 5.2.11 on 2026-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
