# Generated by Django 5.2.11 on 2026-02-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_consultantprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='marketing_roles',
            field=models.ManyToManyField(blank=True, related_name='consultants', to='users.marketingrole'),
        ),
    ]
