# Generated by Django 5.2.11 on 2026-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_marketingrole_consultantprofile_marketing_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BENCH', 'Bench'), ('INACTIVE', 'Inactive'), ('PLACED', 'Placed')], default='ACTIVE', help_text='Current status of the consultant (Admin only)', max_length=20),
        ),
    ]
