# Generated by Django 5.2.11 on 2026-02-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_department_alter_employeeprofile_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
