# Generated by Django 5.2.11 on 2026-02-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_manage_consultants',
            field=models.BooleanField(default=False, help_text='Designates whether this employee can add, edit, or delete consultants.'),
        ),
    ]
