# Generated by Django 5.2.11 on 2026-02-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employeeprofile_can_manage_consultants'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='base_resume_text',
            field=models.TextField(blank=True),
        ),
    ]
