# Generated by Django 5.2.11 on 2026-04-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_organisation_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='available_from',
            field=models.DateField(blank=True, help_text='Earliest date this consultant can start a new engagement.', null=True),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='notice_period',
            field=models.CharField(blank=True, help_text='e.g. 2 weeks, immediate, 30 days.', max_length=80),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the consultant finishes the onboarding wizard.', null=True),
        ),
    ]
