# Generated by Django 5.2.11 on 2026-04-04 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_phase2_ux_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_submissions', models.BooleanField(default=True, help_text='Email when application status or pipeline events affect you.')),
                ('email_interviews', models.BooleanField(default=True, help_text='Email about interviews and scheduling.')),
                ('email_jobs', models.BooleanField(default=True, help_text='Email about job postings and auto-close notices.')),
                ('email_system', models.BooleanField(default=True, help_text='Email for system and account messages.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
