# Generated by Django 5.2.13 on 2026-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_user_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingrole',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='marketingrole',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingrole',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='marketingrole',
            name='match_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Lowercase keyword phrases matched against normalized title+description for auto-classification'),
        ),
        migrations.AddField(
            model_name='marketingrole',
            name='top_category',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('NON_IT', 'Non-IT / Business'), ('ENGINEERING', 'Engineering (Non-IT)'), ('HEALTHCARE', 'Healthcare & Clinical'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
