# Generated by Django 5.2.13 on 2026-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='founding_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='funding_amount',
            field=models.CharField(blank=True, help_text="Free-text funding signal (e.g. '$120M total raised').", max_length=128),
        ),
        migrations.AddField(
            model_name='company',
            name='funding_stage',
            field=models.CharField(blank=True, help_text='e.g. Bootstrapped, Seed, Series A, Public.', max_length=64),
        ),
    ]
