# Generated by Django 5.2.13 on 2026-04-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_founding_year_company_funding_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_count_band',
            field=models.CharField(blank=True, help_text='Normalized employee count band used by resume filtering.', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='funding_total_usd',
            field=models.BigIntegerField(blank=True, help_text='Normalized funding total in USD when available.', null=True),
        ),
    ]
