# Generated by Django 5.2.13 on 2026-05-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_employee_count_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged by Jarvis as a possible duplicate. Needs human review.'),
        ),
        migrations.AddField(
            model_name='company',
            name='possible_duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Fuzzy-matched candidate — review before merging.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='companies.company'),
        ),
    ]
