# Generated by Django 5.2.11 on 2026-02-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0004_submissionresponse'),
        ('users', '0010_employeeprofile_can_manage_consultants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('round', models.CharField(choices=[('SCREENING', 'Screening'), ('TECHNICAL', 'Technical'), ('MANAGERIAL', 'Managerial'), ('HR', 'HR'), ('OTHER', 'Other')], default='SCREENING', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='users.consultantprofile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='submissions.applicationsubmission')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
