# Generated by Django 5.2.11 on 2026-04-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='video_link',
            field=models.URLField(blank=True, help_text='Zoom, Meet, Teams, or other meeting URL.'),
        ),
    ]
