# Generated by Django 5.2.11 on 2026-04-04 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews_app', '0002_phase2_ux_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField(default=3, help_text='1–5 overall.')),
                ('technical_rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5 optional.', null=True)),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5 optional.', null=True)),
                ('strengths', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('STRONG_YES', 'Strong yes'), ('YES', 'Yes'), ('MAYBE', 'Maybe'), ('NO', 'No'), ('STRONG_NO', 'Strong no')], default='MAYBE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='interviews_app.interview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
